#!/usr/bin/env python

import sys
import os
import socket
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("target_slave_dir")
args = parser.parse_args()

print "hostname:%s" % socket.gethostname()
os.chdir(args.target_slave_dir)

from twisted.scripts import twistd
argv = ["twistd", "--no_save", "--nodaemon", "--logfile=twistd.log", "--python=buildbot.tac"]
sys.argv = argv

run = twistd.run
run()
