#!/bin/zsh

pushd /work/fordas/buildbot
source activate

mkdir -p /scratch/USERS/fordas/buildbot
pushd /scratch/USERS/fordas/buildbot

buildslave create-slave -r dev_slave_`hostname` dig18 `hostname` dev
